### ISSUE TITLE
do you have method similiar to VBA PivotFields.AutoGroup？

### ISSUE THREAD

**Issue by learnml2020** [OfficeDev/office-scripts-docs-reference#253]
[Enter feedback here]
Hi，is autoGroup method in VBA available in excel script? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4656d1a-1abf-987a-7257-ed99d47a9ca1
* Version Independent ID: 3489a44c-e985-c2c5-e4a0-c1e800771f8c
* Content: [ExcelScript.PivotField interface - Office Scripts](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.pivotfield?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfield.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfield.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @learnml2020,

Thanks for the question. There is not a method equivalent to AutoGroup in Office Scripts. I'll pass along this parity request to the feature crew. I'd also recommend sending the ask for this Office Scripts method through the **Help** > **Feedback** button in Excel. That way, you can include some details about the scenario you're trying to accomplish.

I'm going to close the issue, since there's no action to be taken in the documentation.
