### ISSUE TITLE
Using `excel.d.ts` in another project

### ISSUE THREAD

**Issue by HoldYourWaffle** [OfficeDev/office-scripts-docs-reference#304]
`office-js-docs-reference` [uses DT as the source of truth](https://github.com/OfficeDev/office-js-docs-reference/blob/main/DocumentationToolingNotes.md#type-definition-files) for its type definitions, which can be conveniently installed in a project with [`@types/office-js`](https://www.npmjs.com/package/@types/office-js). Is there an equivalent for Office Scripts?

There seem to be two versions of `excel.d.ts` in this repository:
- [generate-docs/script-inputs/excel.d.ts](https://github.com/OfficeDev/office-scripts-docs-reference/blob/main/generate-docs/script-inputs/excel.d.ts) (`declare` syntax)
- [generate-docs/api-extractor-inputs-excel/excel.d.ts](https://github.com/OfficeDev/office-scripts-docs-reference/blob/main/generate-docs/api-extractor-inputs-excel/excel.d.ts) (`export` syntax)

The latter seems to get generated based on the first by `GenerateDocs.sh`.

Can this first file be considered a "source of truth", or is there a better place to get these type definitions from?

**Comment by HoldYourWaffle** [comment]
Aaah interesting, that makes sense, thanks for the clarification!

Are there any plans to publish these definitions as an npm package, like `office-js`?
I could write a script to download the file from this repository, but that seems a little janky :P

**Comment by AlexJerabek** [comment]
We actually discourage people from using the npm package for `office-js`. It's better to use what's in the [CDN](https://appsforoffice.microsoft.com/lib/1/hosted/office.js) because that'll always be up-to-date.

We have no plans to publish the `@types` of Office Scripts, since the only consumption of them is in the in-client Code Editor. What are you looking to do with the type definitions?
