### ISSUE TITLE
Document supported ECMAScript version

### ISSUE THREAD

**Issue by HoldYourWaffle** [OfficeDev/office-scripts-docs-reference#306]
## Article URL
[Office Scripts Code Editor environment](https://learn.microsoft.com/en-us/office/dev/scripts/overview/code-editor-environment)

## Issue
The article listed above mentions that Office Scripts are written in JavaScript/TypeScript, but it doesn't mention which version.
Based on some trial and error I'm fairly confident that (as of Excel version 2310), functions up to ES2023 seem to be supported, but the typings appear to be stuck at ES2018. For example:
```ts
promise.finally(...) // ES2018, works
array.flat() // ES2019, works at runtime, but editor shows a type error
array.findLast(...) // ES2023, works at runtime, but editor shows a type error
```
Syntax features seem to only be supported up to TS 3.7, see #305.

This is a little annoying, but easily """fixed""" with a sinful `@ts-nocheck` comment at the top or through (less cursed) indexed-access (e.g. `array['flat']()`).
Either way, I'd love to see some official documentation on this :)

**Comment by AlexJerabek** [comment]
Hi @HoldYourWaffle,

The type definitions are limited by the TypeScript version, which is not as up-to-date as the JavaScript version used by Office Scripts. However, the JavaScript version may be different in the desktop, web, and Power Automate implementations of Excel. Given that, I'd advise against used types not contained in the IntelliSense unless you've done sufficient cross-platform testing.

I'm going to close this issue, since it's effectively the same as #305. I'm working on another follow-up for that thread to help provide some clarity and insight into the future product direction. I'd just checking with engineering on the accuracy of things so I don't erroneously commit to something in public.
