### ISSUE TITLE
how to bind to events?

### ISSUE THREAD

**Issue by abiarge** [OfficeDev/office-scripts-docs-reference#40]
it's not documented how to bind to events. If it's not yet supported, when? I find it essential to build automations...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ccbd23-81a9-a060-bc0f-b68abdff3c08
* Version Independent ID: be11a039-e151-51fc-68c8-44b46fcc9032
* Content: [Excel.Binding class - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excel/excel.binding)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.binding.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.binding.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @abiarge, 

Office Scripts [do not support events](https://docs.microsoft.com/en-us/office/dev/scripts/resources/add-ins-differences#apis). We are working towards [Power Automate](https://flow.microsoft.com/) integration, so you can trigger scripts through events outside of Excel. We do have plans for more in-Excel triggers, but don't have a committed release timeline yet. Tagging @danielgwilson for awareness around your ask.

If you have a specific event you need, please request the feature in [UserVoice](https://excel.uservoice.com/forums/274580-excel-for-the-web?category_id=143439). The Office Scripts feature is still in preview and we're actively trying to incorporate user suggestions. UserVoice is one way we collect and prioritize those suggestions.

You can also look into [Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/) as an automation solution. The [Excel JavaScript API has several events](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events) you could use in your solution, if you decide to go the add-in route.

I'm going to close this issue, since issue in this repo are intended to track problems with the documentation. Please let me know if you have any other questions.

**Comment by abiarge** [comment]
Hi,

Thanks for your response, but just a small question when going the add-in route: can the add-in interfere with the canvas apps connection to Excel Online? I’m asking because, using this connector, you cannot use formulas either.

**Comment by gergzk** [comment]
Hi @abiarge 
To clarify, do you mean the Power Apps canvas-apps connector?
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list

I'm not familiar with it, but does it not work with functions in Excel because it has trouble getting the computed values? 

Assuming the above is the case, these would be unaffected by using an add-in. The add-in can read/write values in whatever format you want (for example, you can do computations in the add-in and write them back as values to Excel) - basically, it can do what a user can do manually. The rest are details for your scenario. 

If the above is not the case, I can answer again after clarification.

**Comment by abiarge** [comment]
Hi,

You assumed right. It’s correct. However, I still have a doubt: is anyway possible the add-in doesn’t have to be triggered manually by the user? I’m only seeing documentation related to showing a “taskpane” where the user interacts with the add-in. However, I need the add-in to act as a “daemon” in the sense that it subscribes to table changes and executes custom code based on those changes whether the Excel Online file is open or not.

Does “excel custom functions” provide support for this scenario?

Thanks in advance,

**Comment by gergzk** [comment]
Ah, I see. 

The add-in can register for an event (eg: onWorksheetChanged), but needs to be running in a session for that event to trigger its behavior. In your case, you would need a user to perform an action and have the add-in running already. It would not perform its effect if the user didn't already invoke it, refused to let it run, or a change was made on a platform that doesn't support add-ins (eg: via a Graph call). I assume a Graph call is what you have in mind for a change where the file is not open? 

Custom functions is probably closest to what you want of the features I'm aware of. It allows you to create a function you can reference in the workbook which would automatically run as part of the calc chain. There are two details I'm not sure of for your scenario:
1. These are also excel functions, so they may run into the same functions issue you saw with the canvas-apps connector
2. The custom function should run anytime the file is opened by a user - but I'm not sure what happens if the file isn't opened when the change is made, and is then consumed via the connector.

You should be able to prototype a solution for either approach (events, custom functions) using Script Lab (to avoid having to create a whole add-in) to see if it works for you:
https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab

**Comment by abiarge** [comment]
Hum,

Alright, I’ll give it a try, but honestly, it doesn’t sound like it’s going to work. I was hoping office scripts for excel online would have something like Google’s spreadsheets, where you can define any trigger such as:
[cid:image001.jpg@01D638CE.E0D6A4B0]

Thanks anyway!
